apiVersion: v1
kind: Service
metadata:
  
  labels:
    app: frontend
  name: frontend
  namespace: kiran
 
spec:
 
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: 8085-8085
    port: 8085
    protocol: TCP
    targetPort: 8085
  selector:
    app: frontend
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
